[package]
name = "LaBrain"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["id_derive"]

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
directories = "6.0.0"
id_derive = { path = "./id_derive/" }
rusqlite = "0.33.0"
